trigger:
  branches:
    include:
    - master
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/

stages:
- stage: Build
  variables:
    TreatWarningsAsErrors: true
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    BuildConfiguration: Release
    BuildPlatform: Any CPU
    codecov_token: e300ab17-4cd6-43b5-8292-e824cb320ed3
    ci_feed: 6ed146e5-8e9c-46d6-a40f-da9367ed50cd/c20edbb7-8403-4456-8f43-f46b47e360b1
    NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages
    GeneratePInvokesTxt: true
  jobs:
  - template: azure-pipelines/build.yml


