steps:
- task: NuGetCommand@2
  displayName: Push packages to CI feed
  inputs:
    command: push
    packagesToPush: bin/$(BuildConfiguration)/Packages/*.nupkg
    nuGetFeedType: internal
    publishVstsFeed: $(ci_feed)
    allowPackageConflicts: true
  condition: and(succeeded(), ne(variables['ci_feed'], ''), ne(variables['Build.Reason'], 'PullRequest'), false)
